model:
  seq_len: 70
  input_dim: 2
  e_node: 48
  hidden_dim: 20
  c_node: 40
  out_node: 4
  strategy: Deterministic
  bias:
    Gaussian: -1
    Laplace: -1
    Cauchy: -3

train:
  method: mcd
  num_epochs: 500
  encoder_lr: 0.0001
  classifier_lr: 0.00002
  num_b: 1
  num_c: 1
  nu:
    Gaussian: 0.001
    Laplace: 0.001
    Cauchy: 0.001
